package com.cprt.advancedauction.theme

import androidx.compose.ui.graphics.Color

internal val colorLightPrimary = Color(0xFF006497)
internal val colorLightOnPrimary = Color(0xFFffffff)
internal val colorLightPrimaryContainer = Color(0xFFcbe6ff)
internal val colorLightOnPrimaryContainer = Color(0xFF161c22)
internal val colorLightSecondary = Color(0xFF006780)
internal val colorLightOnSecondary = Color(0xFFffffff)
internal val colorLightSecondaryContainer = Color(0xFFb3ebff)
internal val colorLightOnSecondaryContainer = Color(0xFF001f29)
internal val colorLightTertiary = Color(0xFF385ba8)
internal val colorLightOnTertiary = Color(0xFFffffff)
internal val colorLightTertiaryContainer = Color(0xFFd9e2ff)
internal val colorLightOnTertiaryContainer = Color(0xFF001848)
internal val colorLightError = Color(0xFFba1b1b)
internal val colorLightErrorContainer = Color(0xFFffdad4)
internal val colorLightOnError = Color(0xFFffffff)
internal val colorLightOnErrorContainer = Color(0xFF410001)
internal val colorLightBackground = Color(0xFFfefbff)
internal val colorLightOnBackground = Color(0xFF1b1b1f)
internal val colorLightSurface = Color(0xFFfefbff)
internal val colorLightOnSurface = Color(0xFF1b1b1f)
internal val colorLightSurfaceVariant = Color(0xFFdee3ea)
internal val colorLightOnSurfaceVariant = Color(0xFF41474d)
internal val colorLightOutline = Color(0xFF72777e)
internal val colorLightInverseOnSurface = Color(0xFFf2f0f5)
internal val colorLightInverseSurface = Color(0xFF303033)
internal val colorLightInversePrimary = Color(0xFF8ecdff)
internal val colorLightShadow = Color(0xFF000000)

internal val colorDarkPrimary = Color(0xFF8ecdff)
internal val colorDarkOnPrimary = Color(0xFF003351)
internal val colorDarkPrimaryContainer = Color(0xFF004b74)
internal val colorDarkOnPrimaryContainer = Color(0xFFcbe6ff)
internal val colorDarkSecondary = Color(0xFF5cd5fb)
internal val colorDarkOnSecondary = Color(0xFF003543)
internal val colorDarkSecondaryContainer = Color(0xFF004e61)
internal val colorDarkOnSecondaryContainer = Color(0xFFb3ebff)
internal val colorDarkTertiary = Color(0xFFb0c6ff)
internal val colorDarkOnTertiary = Color(0xFF002b72)
internal val colorDarkTertiaryContainer = Color(0xFF1b438f)
internal val colorDarkOnTertiaryContainer = Color(0xFFd9e2ff)
internal val colorDarkError = Color(0xFFffb4a9)
internal val colorDarkErrorContainer = Color(0xFF930006)
internal val colorDarkOnError = Color(0xFF680003)
internal val colorDarkOnErrorContainer = Color(0xFFffdad4)
internal val colorDarkBackground = Color(0xFF1b1b1f)
internal val colorDarkOnBackground = Color(0xFFe3e1e6)
internal val colorDarkSurface = Color(0xFF1b1b1f)
internal val colorDarkOnSurface = Color(0xFFe3e1e6)
internal val colorDarkSurfaceVariant = Color(0xFF41474d)
internal val colorDarkOnSurfaceVariant = Color(0xFFc2c7ce)
internal val colorDarkOutline = Color(0xFF8b9198)
internal val colorDarkInverseOnSurface = Color(0xFF1b1b1f)
internal val colorDarkInverseSurface = Color(0xFFe3e1e6)
internal val colorDarkInversePrimary = Color(0xFF006497)
internal val colorDarkShadow = Color(0xFF000000)

internal val seed = Color(0xFF568bb5)
internal val error = Color(0xFFba1b1b)
